# Generated by Django 6.0.7 on 2026-08-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_pppoeevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pppoeevent',
            name='raw_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pppoeevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CONNECTION', 'Connection'), ('AUTH_FAILURE', 'Authentication Failure'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pppoeevent',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
