# Generated by Django 6.0.7 on 2026-08-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_pppoeevent_raw_message_alter_pppoeevent_event_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pppoeevent',
            name='log_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
