# Generated by Django 6.0.7 on 2026-08-13 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_pppoeevent_log_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPPoEClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('mac_address', models.CharField(max_length=50)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('ac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.accessconcentrator')),
            ],
        ),
    ]
