# Generated by Django 6.0.7 on 2026-08-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_pppoeclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pppoeevent',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
