# Generated by Django 6.0.7 on 2026-08-18 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_alter_pppoeevent_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pppoeevent',
            name='event_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CONNECTED', 'Connection'), ('AUTH_FAILURE', 'Authentication Failure'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
