# Generated by Django 6.0.7 on 2026-08-18 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_alter_pppoeevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessconcentrator',
            name='encrypted_password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accessconcentrator',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
