# Generated by Django 6.0.7 on 2026-08-28 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_accessconcentrator_encrypted_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PPPoETrafficHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tx_bits_per_second', models.BigIntegerField(default=0)),
                ('rx_bits_per_second', models.BigIntegerField(default=0)),
                ('tx_packets_per_second', models.BigIntegerField(default=0)),
                ('rx_packets_per_second', models.BigIntegerField(default=0)),
                ('fp_tx_bits_per_second', models.BigIntegerField(default=0)),
                ('fp_rx_bits_per_second', models.BigIntegerField(default=0)),
                ('fp_tx_packets_per_second', models.BigIntegerField(default=0)),
                ('fp_rx_packets_per_second', models.BigIntegerField(default=0)),
                ('tx_drops_per_second', models.BigIntegerField(default=0)),
                ('rx_drops_per_second', models.BigIntegerField(default=0)),
                ('tx_queue_drops_per_second', models.BigIntegerField(default=0)),
                ('tx_errors_per_second', models.BigIntegerField(default=0)),
                ('rx_errors_per_second', models.BigIntegerField(default=0)),
                ('ac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pppoe_traffic_history', to='monitor.accessconcentrator')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traffic_history', to='monitor.pppoeclient')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
