# Generated by Django 6.0.7 on 2026-08-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_pppoetraffichistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PPPoETrafficHistory',
        ),
    ]
